# Generated by Django 5.2.8 on 2025-11-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Aluno')),
                ('nota', models.FloatField(verbose_name='Nota Final')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('dados_json', models.JSONField(default=dict, verbose_name='Detalhes da Prova')),
            ],
            options={
                'verbose_name': 'Prova Entregue',
                'verbose_name_plural': 'Provas Entregues',
                'ordering': ['-data_envio'],
            },
        ),
    ]
